services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - ${ARR}Prowlarr/config:/config
      - ${ARR}Prowlarr/backup:/data-vault/backup
      - $/data/downloads/qbittorrent/completed
    ports:
      - 9696:9696
    restart: unless-stopped
    env_file:
      - '.env'
      
  homarr:
    image: linuxserver/homarr:latest
    container_name: homarr
    volumes:
      - ${ARR}Homarr/config:/config
      - ${ARR}Homarr/backup:/data-vault/backup
      - $/data/downloads/